---

- name: make sure docker from distro is not installed
  yum:
    name: "{{ item }}"
    state: absent
  with_items:
    - docker
    - docker-common
    - container-selinux
    - docker-selinux
    - docker-engine

- name: install yum-utils
  yum:
    name: yum-utils
    state: present

- name: install docker repository
  command:  yum-config-manager --add-repo "https://download.docker.com/linux/centos/docker-ce.repo"

- name: Install docker
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - docker-ce
    - python-docker-py

- name: making sure pip installed
  shell: curl -sSL https://bootstrap.pypa.io/get-pip.py | python
